name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "doc/*.rst"
  schedule:
    - cron: "0 17 * * 0"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements_test.txt
      - name: "Flake8"
        run: flake8 gallery demo

  pytest:
    name: Python ${{ matrix.python-version }} / Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: ["~=3.1.0", "~=3.2.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('tests/requirements_test.txt') }}-${{ matrix.django-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements_test.txt
          pip uninstall -y Django
          pip install Django${{ matrix.django-version }}
          npm install
      - name: Install OS dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install gettext
      - name: Run pytest
        run: |
          pytest --cov-config=setup.cfg --cov-report=xml --cov=.
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
