name: galleryfield-ui js
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  frontend:
    name: Lint JS/build frontend (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install

    - name: ESLint
      run: npx eslint galleryfield/static/js/*.js

    - name: Rollup build
      run: npm run build
